version: '3.8'
services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=falihax
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    env_file:
      - .env
